project_id = "mrcypdyivfprvvirnwtq"

[functions.paystack-bank]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.check-signup-limit]
verify_jwt = false

[functions.advertiser-verify-email]
verify_jwt = false

[functions.generate-loi-pdf]
verify_jwt = false

[functions.advertiser-loi-downloaded]
verify_jwt = false
